version: "3.9"

services:
  python_fastapi:
    image: python_fastapi
    build:
      context: ./pyf
    environment: 
      - POSTGRES_USER=gql
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=data

  python_tornado:
    image: python_tornado
    build:
      context: ./pyt
    ports:
      - 50002:80

  js:
    image: js
    build: 
      context: ./js
    environment:
      NODE_ENV: development

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=gql
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=data
    
  nginx:
    build:
      context: ./nginx
    ports:
      - 50080:80
    depends_on:
      - postgres
      - js
      - python_fastapi
      - python_tornado 
