version: "3.9"

services:
  apollo:
    image: apollo
    build:
      context: ./apollo

  ug_gql:
    image: ug_gql
    build:
      context: ./ug_gql
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=data
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=data
    
  nginx:
    build:
      context: ./nginx
    ports:
      - 50080:80
    depends_on:
      - postgres
      - apollo


